name: build-containerd-image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login
      run: echo "${{secrets.PASSWORD}}" | docker login -u "${{secrets.USERNAME}}" --password-stdin
      
    - name: Build
      run: docker build . --file Dockerfile --tag containerd/ctrimage
      
    - name: Push
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/heads/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo VERSION=$VERSION
        docker tag containerd/ctrimage "${{secrets.USERNAME}}"/ctrimage:$VERSION
        docker push "${{secrets.USERNAME}}"/ctrimage:$VERSION
